spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/settler
    username: settler
    password: devpass
    driver-class-name: org.postgresql.Driver
    hikari:
      register-mbeans: false
      pool-name: HikariPool-1
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: none  # Flyway manages schema, don't auto-create
    properties:
      hibernate:
        org:
          hibernate:
            dialect:
              PostgreSQLDialect:
        jdbc.time_zone: UTC
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    validate-on-migrate: true
    repair-before-migrate: true
    schemas: public

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web: info
    com.settler: debug

jwt:
  secret: "SETTLER_SUPER_SECRET_KEY_1234567890"
  expiration-ms: 7776000000  # 24 hours

lifecycle:
  timeout-per-shutdown-phase: 10s

