spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/settler
    username: settler
    password: devpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Flyway manages schema, don't auto-create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        jdbc.time_zone: UTC
        format_sql: true
        show_sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    validate-on-migrate: true

server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web: info
    com.settler: debug

jwt:
  secret: "SETTLER_SUPER_SECRET_KEY_1234567890"
  expiration-ms: 86400000  # 24 hours

